branches: {only: [master, develop]}
sudo: false
language: python
python: 3.8
cache: pip

matrix:
  include:
    - name: Unit tests
      install: pip install -r requirements-test.txt
      before_script:
        - pip install -e .
      script: pytest -ra -vv --doctest-modules --cov=.
      after_success: pip install codecov && codecov

    - name: Code style
      install: pip install -r requirements-test.txt
      script:
        - black --check .
        - ruff check .
